# Generated by Django 5.2.6 on 2025-09-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("AADHAR", "Aadhar Card"), ("PASSPORT", "Passport")],
                        max_length=10,
                    ),
                ),
                ("pan_number", models.CharField(max_length=10)),
                ("pan_card_image", models.ImageField(upload_to="kyc/pan/")),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "aadhar_front_image",
                    models.ImageField(blank=True, null=True, upload_to="kyc/aadhar/"),
                ),
                (
                    "aadhar_back_image",
                    models.ImageField(blank=True, null=True, upload_to="kyc/aadhar/"),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "passport_front_image",
                    models.ImageField(blank=True, null=True, upload_to="kyc/passport/"),
                ),
                (
                    "passport_back_image",
                    models.ImageField(blank=True, null=True, upload_to="kyc/passport/"),
                ),
                ("selfie_image", models.ImageField(upload_to="kyc/selfies/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
